### ISSUE TITLE
启动插件安装内核出错

### ISSUE THREAD

**Issue by Teares** [noneplugin/nonebot-plugin-boardgame#11]
![image](https://user-images.githubusercontent.com/81464000/174435550-db1693b9-cad8-4e88-a513-2937506f3d11.png)
![image](https://user-images.githubusercontent.com/81464000/174435582-48a03873-c0d3-433c-8081-3c77e70e8ca5.png)
![image](https://user-images.githubusercontent.com/81464000/174435589-35310201-32ce-406f-af18-1137e9056d56.png)

**Comment by MeetWq** [comment]
去 [nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender) 问
