### ISSUE TITLE
安装时报错，html_render插件也安装了，不知道啥情况

### ISSUE THREAD

**Issue by 2018PAN** [noneplugin/nonebot-plugin-boardgame#15]
![image](https://user-images.githubusercontent.com/41419312/215753707-147d2fb4-ee6d-4e22-a0db-be49177d918f.png)

**Comment by MeetWq** [comment]
这种情况应该是有别的插件使用了 `nonebot_plugin_htmlrender` 但没有用 `require` 声明
你需要手动加载 `nonebot_plugin_htmlrender`：
在 `bot.py` 里面 `nonebot.load_plugin("nonebot_plugin_htmlrender")`

**Comment by 2018PAN** [comment]
> 这种情况应该是有别的插件使用了 `nonebot_plugin_htmlrender` 但没有用 `require` 声明 你需要手动加载 `nonebot_plugin_htmlrender`： 在 `bot.py` 里面 `nonebot.load_plugin("nonebot_plugin_htmlrender")`

还是报一样的错误

**Comment by MeetWq** [comment]
看看你的 `bot.py` 是怎么写的

**Comment by 2018PAN** [comment]
> 看看你的 `bot.py` 是怎么写的

好像解决了，把init.py中的require("nonebot_plugin_htmlrender")注释掉了，没发现bug

**Comment by MeetWq** [comment]
使用 `require` 是 nonebot 推荐的写法
你这样碰到别的用了 `require` 的插件还会报错（

**Comment by 2018PAN** [comment]
> 使用 `require` 是 nonebot 推荐的写法 你这样碰到别的用了 `require` 的插件还会报错（

好的，我看一下哪个插件调用htmlrender没require，调一下，非常感谢
