### ISSUE TITLE
下棋时报错了

### ISSUE THREAD

**Issue by Pendome** [noneplugin/nonebot-plugin-boardgame#16]
![image](https://user-images.githubusercontent.com/36023464/228458274-7031c514-eb10-46b3-841a-5df8dfdf4e6a.png)
触发下棋指令报错了

**Comment by Pendome** [comment]
Python 3.8.6
用的是火狐的浏览器firefox-1378
windows server2012 R2
nonebot2

**Comment by MeetWq** [comment]
我是说插件的版本

**Comment by MeetWq** [comment]
你机器人启动的时候有没有报错？

**Comment by Pendome** [comment]
> 你机器人启动的时候有没有报错？
![image](https://user-images.githubusercontent.com/36023464/228470323-97552063-5c15-425a-a638-c14689731707.png)

不好意思哈，插件版本是v0.2.1，机器人启动的时候没有报错，一切正常

**Comment by MeetWq** [comment]
可以把DEBUG模式打开看看结果吗？
在 nonebot 的 .env 文件里设置 LOG_LEVEL=DEBUG

**Comment by he0119** [comment]
可以运行一下 `nb datastore history` 后，发一下结果吗？

**Comment by Pendome** [comment]
> 可以把DEBUG模式打开看看结果吗？ 在 nonebot 的 .env 文件里设置 LOG_LEVEL=DEBUG

![image](https://user-images.githubusercontent.com/36023464/228528857-5afbf609-3bc3-46d4-8e8f-fe479462f607.png)
这个是完整的结果了

**Comment by Pendome** [comment]
> 可以运行一下 `nb datastore history` 后，发一下结果吗？

![image](https://user-images.githubusercontent.com/36023464/228529246-d70ac97a-6fc6-46f2-bc7b-a7842144979e.png)
这个是运行之后的结果

**Comment by he0119** [comment]
绝了，怎么是空的。
![image](https://user-images.githubusercontent.com/5219550/228529493-1fd8707c-ecd8-4da9-b00c-030fc8f9bb4f.png)

**Comment by he0119** [comment]
你可以进 site-packages 找到 nonebot_plugin_datastore，然后把 `self._migration_path` 打印出来看看吗？
在这个位置 <https://github.com/he0119/nonebot-plugin-datastore/blob/366b9cf239718d7b5c0f0a6c5663b13a9214b481/nonebot_plugin_datastore/plugin.py#L262>。

**Comment by he0119** [comment]
> 

奇怪啊，位置没错，这个文件夹里有东西吧？

**Comment by Pendome** [comment]
> 奇怪啊，位置没错，这个文件夹里有东西吧？

![image](https://user-images.githubusercontent.com/36023464/228531598-f05bbe94-309f-4575-87e5-59e55a813360.png)
里面是有东西的

**Comment by he0119** [comment]
太离谱了，我不理解……

**Comment by he0119** [comment]
那你还可以打印一下这里的 `str(PluginData(plugin_name).migration_dir)` 吗？

<https://github.com/he0119/nonebot-plugin-datastore/blob/366b9cf239718d7b5c0f0a6c5663b13a9214b481/nonebot_plugin_datastore/script/utils.py#L59>

**Comment by Pendome** [comment]
> 那你还可以打印一下这里的 `str(PluginData(plugin_name).migration_dir)` 吗？
> 
> https://github.com/he0119/nonebot-plugin-datastore/blob/366b9cf239718d7b5c0f0a6c5663b13a9214b481/nonebot_plugin_datastore/script/utils.py#L59

![image](https://user-images.githubusercontent.com/36023464/228533395-8a2b6e3f-2efe-4eef-ac82-9976a4093417.png)

**Comment by he0119** [comment]
> 



> > 那你还可以打印一下这里的 `str(PluginData(plugin_name).migration_dir)` 吗？
> > https://github.com/he0119/nonebot-plugin-datastore/blob/366b9cf239718d7b5c0f0a6c5663b13a9214b481/nonebot_plugin_datastore/script/utils.py#L59
> 
> ![image](https://user-images.githubusercontent.com/36023464/228533395-8a2b6e3f-2efe-4eef-ac82-9976a4093417.png)

😂😂😂我完全不理解了，可能得去看看 alembic 的源代码。
