### ISSUE TITLE
[bug]围棋出现了一方可以一直下的情况

### ISSUE THREAD

**Issue by citydirector** [noneplugin/nonebot-plugin-boardgame#3]
![49@DR5MK}N12TP37J56HH3](https://user-images.githubusercontent.com/45933075/159409806-69351788-41a3-443d-8451-42f2d0b68481.PNG)

**Comment by MeetWq** [comment]
能不能发一下聊天记录截图

**Comment by citydirector** [comment]
· A：围棋
· A 发起了游戏 围棋！[空白棋盘]
· B：落子d3
· 非法落子（全局同形）
· B：落子d4
· B 落子于 D4，下一手轮到 A [棋盘，D4白子]
· B：你试一下落子d16
· A：落子d16（没有回应）
· A：落子d16
· 此处已有落子
· 我：查看棋盘
· [棋盘，D4白子和D16黑子]
· A：落子d10（没有回应）
· B：查看棋局
· [棋盘，D4白子，D10和D16黑子]
· A：落子d9（没有回应）
· A：查看棋局
· [棋盘，D4白子，D9和D10和D16黑子]
· A：我还能连续下？？？
· B：停止下棋
· 游戏已停止

**Comment by MeetWq** [comment]
可以试试现在的版本还有没有bug

**Comment by citydirector** [comment]
暂时没出现了，以后再出现的话再reopen

**Comment by citydirector** [comment]
![image](https://user-images.githubusercontent.com/45933075/160030776-510cab54-b7e3-468c-aa22-e4b860ce75f5.png)
![image](https://user-images.githubusercontent.com/45933075/160030835-4a3fc904-5cf6-4aa1-860d-a064c2bddd6b.png)
![image](https://user-images.githubusercontent.com/45933075/160030891-abc5e396-f86a-4e67-b44b-b961693d0303.png)
![image](https://user-images.githubusercontent.com/45933075/160030947-448d573b-5881-4752-9c82-295ff3b2fdcb.png)

**Comment by citydirector** [comment]
sorry，还是出现了这个问题

**Comment by MeetWq** [comment]
有日志吗，可以看看机器人没发出消息的时候报什么错

**Comment by citydirector** [comment]
> 有日志吗，可以看看机器人没发出消息的时候报什么错

没有，而且现在号又又又被封了（理由是涉嫌诈骗）

**Comment by MeetWq** [comment]
我加了个并发数限制，可以再逝世

**Comment by citydirector** [comment]
> 我加了个并发数限制，可以再逝世

现在的情况是既不会更新棋盘，也不会回应落子（）
只有“查看棋局”有反应，然后一直卡在双方的第一颗棋都下完的时候

**Comment by MeetWq** [comment]
麻烦提供一下log，否则我也不知道是哪里的问题

**Comment by MeetWq** [comment]
新版本改名了，优化了一下逻辑
如果还有问题可以再开issue
